---
- name: download java
  get_url:
    url:    "{{download_url}}" 
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{java_archive}}"

- name: Unpack archive
  unarchive:
    copy: no
    src: "{{java_archive}}"
    creates: "{{java_name}}"
    dest: "{{download_folder}}"
    group: root
    owner: root

- name: Make Java available for system
  alternatives:
    link: /usr/bin/java
    name: java
    path: "{{java_name}}/bin/java"

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no

#- name: Install xauth
#  yum:
#    name: "xorg-x11-xauth"
#    state: present

- name: Install X Window System
  yum:
    name: "@^Server with GUI"
    state: present


- name: Install Xfce desktop
  #shell: yum --enablerepo=epel -y groupinstall xfce-desktop x11
  yum:
    enablerepo: epel
    name: "@Xfce"
    state: present
- name: get default runleveldd
  command: systemctl get-default
  register: runlevel
- name: Set graphical runlevel
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"
- name: is graphical currently active
  command: systemctl is-active graphical.target
  register: graphical
- name: Switch to graphical runlevel
  command: systemctl isolate graphical.target
  when: graphical.stdout != "active"


#- name: Unpack archive
#  become: yes
#  become_user: root
#  vars:
#    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"
#    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
#    download_folder: /opt
#    java_name: "{{download_folder}}/jdk1.8.0_05"
#  command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"
