import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'user' at '6/29/17 10:28 AM' with Gradle 2.3
 *
 * @author user, @date 6/29/17 10:28 AM
 */
public class JavaAWSiotSerialBridgeTest {
    @Test public void testSomeMethod() {
    }
}
